sonar.projectKey=cpp-analysis-test
sonar.projectName=C++ Toolbox
sonar.projectVersion=0.0.0
sonar.sources=src/nael_utils/src
sonar.tests=src/test/src

sonar.exclusions=src/app/src/**,src/test/**
sonar.coverage.exclusions=src/app/src/**,src/test/**
sonar.cpd.exclusions=src/app/src/**,src/test/**
sonar.test.exclusions=src/app/src/**,src/test/**

sonar.cxx.jsonCompilationDatabase=builds/Debug/compile_commands.json
sonar.cxx.cppcheck.reportPath=cppcheck-reports/*.xml
sonar.cxx.coverage.reportPath=coverage-reports/*.xml
