sonar.projectKey=cpp-utils
sonar.projectName=C++ Toolbox
sonar.projectVersion=1.0.0
sonar.sources=src/nael_utils/src
sonar.tests=src/test/src

sonar.exclusions=src/app/src/**,src/test/**
sonar.coverage.exclusions=src/app/src/**,src/test/**
sonar.cpd.exclusions=src/app/src/**,src/test/**
sonar.test.exclusions=src/app/src/**,src/test/**

sonar.cfamily.variants.names=Debug, Release
sonar.cfamily.variants.dir=compilation-databases
sonar.coverageReportPaths=compilation-databases/sonarqube.xml
sonar.cfamily.valgrind.reportsPaths=compilation-databases/**memcheck-results.xml
