sonar.organization=futurmasterdev

sonar.projectKey=futurmasterdev_plns-or-utils

sonar.projectVersion=1.1.0
sonar.sources=src/
sonar.tests=src/test/src

sonar.exclusions=src/app/src/**,src/test/**
sonar.coverage.exclusions=src/app/src/**,src/test/**
sonar.cpd.exclusions=src/app/src/**,src/test/**
sonar.test.exclusions=src/app/src/**,src/test/**

sonar.cfamily.compile-commands=compilation-databases/Debug/compile_commands.json
sonar.coverageReportPaths=compilation-databases/sonarqube.xml
sonar.cfamily.valgrind.reportsPaths=compilation-databases/**memcheck-results.xml
