#[=======================================================================[.rst:
unit_tests
----------

This module defines a ``unit_tests`` build target and helpers to ease
configuring, developing and testing C++ projects.

.. command:: include (unit_tests)

  Does all the work.

  .. code-block:: cmake

    include (unit_tests)

  Creates a ``unit_tests`` target, linked with GoogleTest library (without the
  predefined `main`)

  Also defines a ``run_unit_tests`` target to execute the tests. The call will
  generate a report (XML format) named ``unit_tests-results.xml`` in
  ``${CMAKE_BINARY_DIR}/tests-reports``.

  Additional arguments can be passed by defining the **user-defined** target
  property `UNIT_TESTS_ARGS`.

  Note that tests will be executed and report will be generated only on first
  call, or if the ``unit_tests`` binary has been updated since last call. Thus
  the call to ``run_unit_tests`` should be sufficent to get an up-to-date
  report, with no duplicated execution.

  For use-cases where the `unit_tests` binary is used to execute functional
  tests (as when using FuncTest from EDCppUtils), with fully automated checks
  (meaning no rebuild is necessary for updating the tests), or if only the
  input files are modified, the binary cannot see the modified tests, so the
  witness file generated by run_unit_tests will have to be removed (search for
  `.witness` files in the build directory).

Usage example:

  .. code-block:: cmake

    include(unit_tests)

    set_target_properties (unit_tests
      PROPERTIES
      UNIT_TESTS_ARGS "--lang;${PROJECT_SOURCE_DIR}/lang;--gtest_filter=-ft.*")

    target_sources (unit_tests
      PRIVATE
      src/my_first_test.cc
      src/my_second_test.cc)

    # in case user does not need custom main
    target_link_libraries (unit_tests
      PRIVATE
      GTest::gtest_main)

#]=======================================================================]

cmake_minimum_required (VERSION 3.16)
# 3.2 for add_custom_command (BYPRODUCTS)
# 3.3 for CMP0058

### ===============================================================================================
### Requirements
### ===============================================================================================

find_package (GTest REQUIRED)

include (default_warnings)

enable_testing()

### ===============================================================================================
### Unit tests executable
### ===============================================================================================

add_executable (unit_tests)

set_target_properties (unit_tests
	PROPERTIES
	EXCLUDE_FROM_ALL ON # avoid unnecessary build
	#[[ end of list ]])

set_default_warnings (TARGET unit_tests)

target_link_libraries (unit_tests
	PRIVATE
	GTest::gtest)

### ===============================================================================================
### Automation
### ===============================================================================================

set (unit_tests_reports_path ${CMAKE_BINARY_DIR}/tests-reports)
file (MAKE_DIRECTORY ${unit_tests_reports_path})

add_custom_target (run_unit_tests
	DEPENDS ${unit_tests_reports_path}/unit_tests-results.xml.witness
	COMMENT "Running unit tests")

add_custom_command (OUTPUT ${unit_tests_reports_path}/unit_tests-results.xml.witness
	# Specifying BYPRODUCTS here is not mandatory,
	# but allows Ninja users to later do funny (dependant) things
	# See CMP0058
	BYPRODUCTS ${unit_tests_reports_path}/unit_tests-results.xml
	COMMAND $<TARGET_FILE:unit_tests> --gtest_output=xml:unit_tests-results.xml $<TARGET_PROPERTY:unit_tests,UNIT_TESTS_ARGS>
	COMMAND ${CMAKE_COMMAND} -E touch ${unit_tests_reports_path}/unit_tests-results.xml.witness
	DEPENDS unit_tests
	WORKING_DIRECTORY ${unit_tests_reports_path}
	VERBATIM
	COMMAND_EXPAND_LISTS)

add_test(NAME unit_tests_ctest COMMAND $<TARGET_FILE:unit_tests>)

