name: linting
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: c-linter
        uses: tonybaloney/cppcheck-action@master
        with:
          path: ${{github.workspace}}/src/libutils/
      