# Workflow for C++ project
name: dev-pipeline
# Only for dev
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]
    types: [opened, synchronize, reopened]
# List of actions
jobs:
  cpp_pipeline:
    # Just linux for now
    runs-on: ubuntu-latest
    # Steps
    steps:
    # Checkout sources
    - name: checkout
      uses: actions/checkout@v4
      with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # Get c++ tools
    - name: Get C++ Tools
      uses: KobNael/nael_cpp_action/setup_cpp@draft
    # Install conan
    - name: Get Conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.11.0
    # Release Build
    - name: Release conan build
      uses: KobNael/nael_cpp_action/cmake_build@draft
      with:
        build_type: Release
    # Test
    - name: Release analysis
      uses: KobNael/nael_cpp_action/tests_cpp@draft
      with:
        build_type: Release
    # Debug Build
    - name: Debug conan build
      uses: KobNael/nael_cpp_action/cmake_build@draft
      with:
        build_type: Debug
    # Test
    - name: Debug analysis
      uses: KobNael/nael_cpp_action/tests_cpp@draft
      with:
        build_type: Debug
    # Sonar analysis
    - name: Sonar analysis
      uses: SonarSource/sonarqube-scan-action@v4
      env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Put the name of your token here
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
      with:
          # Consult https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/scanners/sonarscanner/ for more information and options
          args: --debug

