# Workflow for C++ project
name: dev-pipeline

# Only for dev
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "feature/*", "dev", "main" ]

# List of actions
jobs:
  # Call pipeline
  cpp_pipeline:
    # Skip draft PR
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: KobNael/nael_cpp_action/.github/workflows/cpp-workflow.yml@dev
    with:
      WITH_COVERAGE: true
      RUN_SONAR: true
      CHECK_QUALITY_GATE: true
      UPLOAD_ARTIFACT: false
    secrets:
      GH_PAT: "${{ secrets.GH_PAT }}"
      SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
      SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
