# Workflow for C++ project
name: dev-pipeline
# Only for dev
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize, reopened]
# List of actions
jobs:
  build:
    # Just linux for now
    runs-on: ubuntu-latest
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      # Release And Debug
      matrix:
        build_type: [Debug, Release]
    # Steps
    steps:
    # Checkout sources
    - name: checkout
      uses: actions/checkout@v4
      with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # Get c++ tools
    - name: Get C++ Tools
      uses: KobNael/nael_cpp_action/setup_cpp@draft
    # Install conan
    - name: Get Conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.11.0
    # Build
    - name: Cmake build
      uses: KobNael/nael_cpp_action/cmake_build@draft
      with:
        build_type: ${{matrix.build_type}}
    # Test
    - name: Code analysis
      uses: KobNael/nael_cpp_action/tests_cpp@draft
      with:
        build_type: ${{matrix.build_type}}

    # SonarQube Analysis and publish
#    - if: ${{ matrix.build_type == 'Debug' }}
#      name: SonarQube Scan
#      uses: SonarSource/sonarqube-scan-action@v4
#      env:
#        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Put the name of your token here
#        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
#      with:
#        # if you are using using sonarqube 10.5 or earlier, replace sonar.cfamily.compile-commands with sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"
#        # as build-wrapper does not generate a compile_commands.json file before sonarqube 10.6
#        args: >
#          --define sonar.cfamily.compile-commands="${{github.workspace}}/builds/Linux/gcc/13/x86_64/${{matrix.build_type}}/compile_commands.json"

# List of actions
  sonar:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    # Checkout project
    - name: checkout
      uses: actions/checkout@v4
      with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # Download reports
    - name: Download Release reports
      uses: actions/download-artifact@v4
      with:
        name: sonar-results-Release
        path: ./compilation-databases/Release/
    - name: Download Debug reports
      uses: actions/download-artifact@v4
      with:
        name: sonar-results-Debug
        path: ./compilation-databases/Debug/
    # SonarQube Analysis
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Put the name of your token here
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret


